name: mt-seg
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.8=h7f8727e_0
  - pip=23.1.2=py38h06a4308_0
  - python=3.8.16=h955ad1f_4
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - addict==2.4.0
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - colorama==0.4.6
    - contourpy==1.1.0
    - cycler==0.11.0
    - cython==0.29.35
    - fonttools==4.40.0
    - idna==3.4
    - imageio==2.31.1
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - instaboostfast==0.1.2
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - markdown==3.4.3
    - markdown-it-py==3.0.0
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mmcv-full==1.4.2
    - mmdet==2.22.0
    - mmengine==0.7.4
    - mmsegmentation==0.20.2
    - model-index==0.1.11
    - multiscaledeformableattention==1.0
    - networkx==3.1
    - numpy==1.24.3
    - opencv-python==4.7.0.72
    - openmim==0.3.7
    - ordered-set==4.1.0
    - packaging==23.1
    - pandas==2.0.2
    - pillow==9.5.0
    - platformdirs==3.5.3
    - prettytable==3.8.0
    - pycocotools==2.0.6
    - pygments==2.15.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.31.0
    - rich==13.4.2
    - scikit-image==0.21.0
    - scipy==1.10.1
    - six==1.16.0
    - tabulate==0.9.0
    - termcolor==2.3.0
    - terminaltables==3.1.10
    - tifffile==2023.4.12
    - timm==0.4.12
    - tomli==2.0.1
    - torch==1.9.0+cu111
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
    - typing-extensions==4.6.3
    - tzdata==2023.3
    - urllib3==2.0.3
    - wcwidth==0.2.6
    - yapf==0.40.0
    - zipp==3.15.0